### ISSUE TITLE
Explicit dependencies

### ISSUE THREAD

**Issue by Raphux** [joaophi/tailscale-gnome-qs#1]
Just an humble suggestion : README could mention not usually installed dependencies like `gettext`.
When running the command `gnome-extensions install $(BUNDLE_PATH) --force`, it was complaining about not finding the `msgfmt` binary, which is provide by `gettext` package (at least in Ubuntu/Debian).

But I would also agree that this dependency should be carried by the `gnome-extentions` package. So it might more be a distro issue.

Anyway, that was my two cents.

**Comment by joaophi** [comment]
Thanks for the feedback!
Build instructions added to [README](https://github.com/joaophi/tailscale-gnome-qs/blob/master/README.md).
