### ISSUE TITLE
Change the icon when Exit Node feature is in use

### ISSUE THREAD

**Issue by gdonval** [joaophi/tailscale-gnome-qs#12]
The extension is brilliant, truly!

I just wish it would be made clearer when one is using exit nodes (any one of them). I just suggest designing a slightly different icon (with an arrow or anything, really) just to distinguish the default case from any full proxying case. 

A more meaningful alternative would be overlaying a small number which corresponds to the rank of the exit node on the list.

At any rate, keep up with the good work!

**Comment by joaophi** [comment]
Hi, thank you.

It already shows a vpn icon next to the tailscale icon when using an exit node.

![image](https://github.com/joaophi/tailscale-gnome-qs/assets/23062105/f4ba001b-9378-4b62-b4dd-366e8e654bc0)

Are you talking about the quick toggle button?

**Comment by gdonval** [comment]
It doesn't at least on gnome 45. I'll share a picture next time I access my computer.

**Comment by gdonval** [comment]
Ahhh! Nevermind, it *does* get displayed now...
