### ISSUE TITLE
Host list shows original hostnames instead of overridden hostnames

### ISSUE THREAD

**Issue by evandeaubl** [joaophi/tailscale-gnome-qs#2]
I have a couple of hosts that I've overridden their hostname in the Tailscale console, but in the extension host list the original name shows up. If that information is available to the extension, it would be nice for the overridden hostname to show up instead.

**Comment by joaophi** [comment]
Fixed

Update available at https://extensions.gnome.org/extension/6139/tailscale-qs/ and https://github.com/joaophi/tailscale-gnome-qs/actions/runs/5772128109
