### ISSUE TITLE
Request: Clicking Node copies TS IP Address

### ISSUE THREAD

**Issue by techwithjake** [joaophi/tailscale-gnome-qs#5]
It'd be very useful if when clicking on a node that it copies the Tailscale IP address.

**Comment by joaophi** [comment]
Added copy ip on long click https://github.com/joaophi/tailscale-gnome-qs/commit/2800493de14886bf5a669878692a45f51a430428, update avaible at https://extensions.gnome.org/extension/6139/tailscale-qs/
![Captura de tela de 2023-08-31 09-47-17](https://github.com/joaophi/tailscale-gnome-qs/assets/23062105/7281443f-a865-4f23-b241-113810adf992)
