### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by guilhem** [joaophi/tailscale-gnome-qs#6]
Current version fail with gnome 45 with error:
```
import declarations may only appear at top level of a module
```
It's because of:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by joaophi** [comment]
Gnome 45 support released

**Comment by jee-r** [comment]
I'd like to take this opportunity to thank you for this wonderful extension @joaophi . 
Great work :+1:
